/**
 * Native implementation of {@link RunestoneCodec}.
 *
 * Follows `ord`'s `Runestone::encipher` / `Runestone::decipher`
 * (crates/ordinals/src/runestone.rs) and is checked against vectors generated by
 * that crate: see `tests/ord-vectors.test.ts`, which also lists the places where
 * this decoder still differs from ord. The main one: ord deciphers a whole
 * transaction, this deciphers one scriptPubKey, so the two rules that depend on
 * the transaction's output count (edict output, pointer) are only checked when
 * the caller passes `outputCount`.
 *
 * Script bytes are written and parsed here, not with bitcoinjs-lib's
 * `script.compile` / `decompile`. Those apply minimal-push rules: a one-byte push
 * of 1..16 becomes `OP_1`..`OP_16`, which ord reads as a non-push opcode and
 * treats as a cenotaph.
 */

import type { RunestoneCodec } from "./codec.js";
import {
  Tag,
  Flag,
  flagMask,
  RUNESTONE_MAGIC,
  MAX_DIVISIBILITY,
  MAX_SPACERS,
  type DecipherContext,
  type Etching,
  type Edict,
  type Flaw,
  type Runestone,
  type DecipherResult,
} from "./types.js";
import { RUNE_ID_ZERO, runeIdDelta, compareRuneId, type RuneId } from "./rune-id.js";
import { encodeVarint, decodeAllVarints, U128_MAX } from "./varint.js";

const OP_RETURN = 0x6a;
const OP_PUSHDATA1 = 0x4c;
const OP_PUSHDATA2 = 0x4d;
const OP_PUSHDATA4 = 0x4e;

const U32_MAX = 0xffff_ffffn;
const U64_MAX = (1n << 64n) - 1n;

const FLAW_TEXT: Record<Flaw, string> = {
  "edict-output": "edict output greater than transaction output count",
  "edict-rune-id": "invalid rune ID in edict",
  "invalid-script": "invalid script in OP_RETURN",
  opcode: "non-pushdata opcode in OP_RETURN",
  "supply-overflow": "supply overflows u128",
  "trailing-integers": "trailing integers in body",
  "truncated-field": "field with missing value",
  "unrecognized-even-tag": "unrecognized even tag",
  "unrecognized-flag": "unrecognized flag",
  varint: "invalid varint",
};

/** A data push, with the length prefix rust-bitcoin's `push_slice` would write. */
function pushBytes(data: Buffer): Buffer {
  const n = data.length;
  let prefix: Buffer;
  if (n < OP_PUSHDATA1) {
    prefix = Buffer.from([n]);
  } else if (n <= 0xff) {
    prefix = Buffer.from([OP_PUSHDATA1, n]);
  } else if (n <= 0xffff) {
    prefix = Buffer.alloc(3);
    prefix[0] = OP_PUSHDATA2;
    prefix.writeUInt16LE(n, 1);
  } else {
    prefix = Buffer.alloc(5);
    prefix[0] = OP_PUSHDATA4;
    prefix.writeUInt32LE(n, 1);
  }
  return Buffer.concat([prefix, data]);
}

type Payload = { payload: Buffer } | { flaw: Flaw } | undefined;

/**
 * Extract the runestone payload from a scriptPubKey: `OP_RETURN OP_13` followed
 * by data pushes only. Returns `undefined` when the script is not a runestone.
 */
function readPayload(script: Buffer): Payload {
  if (script.length < 2 || script[0] !== OP_RETURN || script[1] !== RUNESTONE_MAGIC) {
    return undefined;
  }

  const parts: Buffer[] = [];
  let i = 2;
  while (i < script.length) {
    const opcode = script[i];
    i += 1;

    let length: number;
    if (opcode < OP_PUSHDATA1) {
      length = opcode; // includes OP_0, an empty push
    } else if (opcode === OP_PUSHDATA1) {
      if (i + 1 > script.length) return { flaw: "invalid-script" };
      length = script[i];
      i += 1;
    } else if (opcode === OP_PUSHDATA2) {
      if (i + 2 > script.length) return { flaw: "invalid-script" };
      length = script.readUInt16LE(i);
      i += 2;
    } else if (opcode === OP_PUSHDATA4) {
      if (i + 4 > script.length) return { flaw: "invalid-script" };
      length = script.readUInt32LE(i);
      i += 4;
    } else {
      return { flaw: "opcode" };
    }

    if (i + length > script.length) return { flaw: "invalid-script" };
    parts.push(script.subarray(i, i + length));
    i += length;
  }

  return { payload: Buffer.concat(parts) };
}

/** `RuneId::new`: block 0 is only valid with tx 0; block is a u64, tx a u32. */
function validRuneId(block: bigint, tx: bigint): RuneId | undefined {
  if (block > U64_MAX || tx > U32_MAX) return undefined;
  if (block === 0n && tx > 0n) return undefined;
  return { block, tx };
}

/** `RuneId::next`: apply a delta-encoded (block, tx) pair with overflow checks. */
function nextRuneId(previous: RuneId, block: bigint, tx: bigint): RuneId | undefined {
  if (block > U64_MAX || tx > U32_MAX) return undefined;
  return validRuneId(
    previous.block + block,
    block === 0n ? previous.tx + tx : tx,
  );
}

export class NativeRunestoneCodec implements RunestoneCodec {
  encipher(runestone: Runestone): Buffer {
    const stream: bigint[] = [];

    const pushTag = (tag: Tag, values: bigint[]): void => {
      for (const v of values) {
        stream.push(BigInt(tag));
        stream.push(v);
      }
    };
    const pushTagOpt = (tag: Tag, value: bigint | undefined): void => {
      if (value !== undefined) pushTag(tag, [value]);
    };

    // ── Etching ──────────────────────────────────────────────────────────────
    const e = runestone.etching;
    if (e) {
      let flags = flagMask(Flag.Etching);
      if (e.terms) flags |= flagMask(Flag.Terms);
      if (e.turbo) flags |= flagMask(Flag.Turbo);

      pushTag(Tag.Flags, [flags]);
      pushTagOpt(Tag.Rune, e.rune);
      pushTagOpt(
        Tag.Divisibility,
        e.divisibility === undefined ? undefined : BigInt(e.divisibility),
      );
      pushTagOpt(
        Tag.Spacers,
        e.spacers === undefined ? undefined : BigInt(e.spacers),
      );
      pushTagOpt(
        Tag.Symbol,
        e.symbol === undefined ? undefined : BigInt(e.symbol),
      );
      pushTagOpt(Tag.Premine, e.premine);

      if (e.terms) {
        pushTagOpt(Tag.Amount, e.terms.amount);
        pushTagOpt(Tag.Cap, e.terms.cap);
        pushTagOpt(Tag.HeightStart, e.terms.heightStart);
        pushTagOpt(Tag.HeightEnd, e.terms.heightEnd);
        pushTagOpt(Tag.OffsetStart, e.terms.offsetStart);
        pushTagOpt(Tag.OffsetEnd, e.terms.offsetEnd);
      }
    }

    // ── Mint / Pointer ───────────────────────────────────────────────────────
    if (runestone.mint) {
      pushTag(Tag.Mint, [runestone.mint.block, runestone.mint.tx]);
    }
    pushTagOpt(
      Tag.Pointer,
      runestone.pointer === undefined ? undefined : BigInt(runestone.pointer),
    );

    // ── Body / Edicts ────────────────────────────────────────────────────────
    const edicts = runestone.edicts ?? [];
    if (edicts.length > 0) {
      stream.push(BigInt(Tag.Body));
      const sorted = [...edicts].sort((a, b) => compareRuneId(a.id, b.id));
      let previous = RUNE_ID_ZERO;
      for (const edict of sorted) {
        const [blockDelta, txValue] = runeIdDelta(previous, edict.id);
        stream.push(blockDelta);
        stream.push(txValue);
        stream.push(edict.amount);
        stream.push(BigInt(edict.output));
        previous = edict.id;
      }
    }

    // ── Serialize ────────────────────────────────────────────────────────────
    const bytes: number[] = [];
    for (const v of stream) bytes.push(...encodeVarint(v));
    const payload = Buffer.from(bytes);

    // Like ord: the whole payload in one push, and no push at all when empty.
    const prefix = Buffer.from([OP_RETURN, RUNESTONE_MAGIC]);
    return payload.length === 0
      ? prefix
      : Buffer.concat([prefix, pushBytes(payload)]);
  }

  decipher(scriptPubKey: Buffer, context: DecipherContext = {}): DecipherResult {
    const { outputCount } = context;
    const runestone: Runestone = {};
    const flaws: Flaw[] = [];
    const result = (): DecipherResult => ({
      runestone,
      cenotaph: flaws.length > 0,
      flaw: flaws[0],
      flaws: flaws.map((f) => FLAW_TEXT[f]),
    });

    const read = readPayload(Buffer.from(scriptPubKey));
    if (read === undefined) {
      return {
        runestone,
        cenotaph: true,
        flaws: ["not a runestone: missing OP_RETURN OP_13 prefix"],
      };
    }
    if ("flaw" in read) {
      flaws.push(read.flaw);
      return result();
    }

    let integers: bigint[];
    try {
      integers = decodeAllVarints(read.payload);
    } catch {
      flaws.push("varint");
      return result();
    }

    // ── Message: tag/value fields, then the edict body ───────────────────────
    const fields = new Map<bigint, bigint[]>();
    const edicts: Edict[] = [];

    for (let i = 0; i < integers.length; i += 2) {
      const tag = integers[i];

      if (tag === BigInt(Tag.Body)) {
        let previous = RUNE_ID_ZERO;
        for (let j = i + 1; j < integers.length; j += 4) {
          if (j + 4 > integers.length) {
            flaws.push("trailing-integers");
            break;
          }
          const id = nextRuneId(previous, integers[j], integers[j + 1]);
          if (id === undefined) {
            flaws.push("edict-rune-id");
            break;
          }
          const output = integers[j + 3];
          if (
            output > U32_MAX ||
            (outputCount !== undefined && output > BigInt(outputCount))
          ) {
            flaws.push("edict-output");
            break;
          }
          edicts.push({ id, amount: integers[j + 2], output: Number(output) });
          previous = id;
        }
        break;
      }

      const value = integers[i + 1];
      if (value === undefined) {
        flaws.push("truncated-field");
        break;
      }
      const values = fields.get(tag) ?? [];
      values.push(value);
      fields.set(tag, values);
    }

    /**
     * ord's `Tag::take`: consume the first `n` values of a field if `convert`
     * accepts them. A rejected or short field is left in place, where an even
     * tag later counts as unrecognized.
     */
    const take = <T>(
      tag: Tag,
      n: number,
      convert: (values: bigint[]) => T | undefined,
    ): T | undefined => {
      const values = fields.get(BigInt(tag));
      if (values === undefined || values.length < n) return undefined;
      const converted = convert(values.slice(0, n));
      if (converted === undefined) return undefined;
      values.splice(0, n);
      if (values.length === 0) fields.delete(BigInt(tag));
      return converted;
    };
    const u128 = ([v]: bigint[]): bigint => v;
    const u64 = ([v]: bigint[]): bigint | undefined => (v <= U64_MAX ? v : undefined);

    let flags = take(Tag.Flags, 1, u128) ?? 0n;
    const takeFlag = (flag: Flag): boolean => {
      const mask = flagMask(flag);
      const set = (flags & mask) !== 0n;
      flags &= ~mask;
      return set;
    };

    if (takeFlag(Flag.Etching)) {
      const etching: Etching = {};
      const divisibility = take(Tag.Divisibility, 1, ([v]) =>
        v <= BigInt(MAX_DIVISIBILITY) ? Number(v) : undefined,
      );
      const premine = take(Tag.Premine, 1, u128);
      const rune = take(Tag.Rune, 1, u128);
      const spacers = take(Tag.Spacers, 1, ([v]) =>
        v <= BigInt(MAX_SPACERS) ? Number(v) : undefined,
      );
      // A Rust `char`: a Unicode scalar value, so no surrogates.
      const symbol = take(Tag.Symbol, 1, ([v]) =>
        v <= 0x10ffffn && !(v >= 0xd800n && v <= 0xdfffn) ? Number(v) : undefined,
      );

      if (rune !== undefined) etching.rune = rune;
      if (divisibility !== undefined) etching.divisibility = divisibility;
      if (spacers !== undefined) etching.spacers = spacers;
      if (symbol !== undefined) etching.symbol = symbol;
      if (premine !== undefined) etching.premine = premine;

      if (takeFlag(Flag.Terms)) {
        const cap = take(Tag.Cap, 1, u128);
        const heightStart = take(Tag.HeightStart, 1, u64);
        const heightEnd = take(Tag.HeightEnd, 1, u64);
        const amount = take(Tag.Amount, 1, u128);
        const offsetStart = take(Tag.OffsetStart, 1, u64);
        const offsetEnd = take(Tag.OffsetEnd, 1, u64);
        etching.terms = { amount, cap, heightStart, heightEnd, offsetStart, offsetEnd };
      }
      etching.turbo = takeFlag(Flag.Turbo);
      runestone.etching = etching;
    }

    const mint = take(Tag.Mint, 2, ([block, tx]) => validRuneId(block, tx));
    if (mint !== undefined) runestone.mint = mint;

    const pointer = take(Tag.Pointer, 1, ([v]) =>
      v <= U32_MAX && (outputCount === undefined || v < BigInt(outputCount))
        ? Number(v)
        : undefined,
    );
    if (pointer !== undefined) runestone.pointer = pointer;
    if (edicts.length > 0) runestone.edicts = edicts;

    const etching = runestone.etching;
    if (etching) {
      const supply =
        (etching.premine ?? 0n) +
        (etching.terms?.cap ?? 0n) * (etching.terms?.amount ?? 0n);
      if (supply > U128_MAX) flaws.push("supply-overflow");
    }
    if (flags !== 0n) flaws.push("unrecognized-flag");
    if ([...fields.keys()].some((tag) => tag % 2n === 0n)) {
      flaws.push("unrecognized-even-tag");
    }

    return result();
  }
}

/** A ready-to-use shared instance of the native codec. */
export const nativeRunestoneCodec = new NativeRunestoneCodec();
